### ISSUE TITLE
How about creation / deletion by namespace ?

### ISSUE THREAD

**Issue by HaraShun** [localhost9292/kubernetes.rb#2]
クラスターを都度都度作成するのではなく、
namespace を切って、作成＆削除するようにするのはどうか？

▼ 「namespace」 とは
KubernetesにはNamespaceと呼ばれる仮想的なKubernetesクラスタの分離機能が存在します。

『Kubernetesの基礎 | Think IT（シンクイット） 』より
（https://thinkit.co.jp/article/13542）

▼ 例
例えば、「08_gitlab」はそうなっています。
kubernetes.rb/README.md at master · HaraShun/kubernetes.rb : https://github.com/HaraShun/kubernetes.rb/blob/master/08_gitlab/README.md

**Comment by yhirano55** [comment]
namespace切るの便利そうですね。とてもシンプルだし、これを削除してクリーンアップできるのは、とてもよいと思いました。

```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: gitlab
```
